INSERT INTO COURSE(ID,TITLE,DESCRIPTION,FEE) VALUES (1,'CC','CLOUD COMPUTING',30.0);
INSERT INTO COURSE(ID,TITLE,DESCRIPTION,FEE) VALUES (2,'RP','RESEARCH PRACTICE',10.0);
INSERT INTO COURSE(ID,TITLE,DESCRIPTION,FEE) VALUES (3,'PHY','PHYSICS',20.0);